[package]
name = "slms"
version = "1.0.2"
authors = ["Jörn Roddelkopf"]

[dependencies]
chrono = "*"
lazy_static = "*"
daemonize="*"
pnet="*"
sys-info = "*"
uuid={version = "*", features = ["v4"]}
log = "*"
simplelog = "*"